// Replication archive builder. Everything a stranger needs to reproduce every
// corrected statistic OUTSIDE Concord: frozen instruments (full prompts),
// the codebook, gold labels with inclusion probabilities, machine outputs,
// certificate agreement stats, analysis specs/results, and generated R +
// Python scripts that re-derive the DSL-corrected estimates from the CSVs.
//
// Determinism: members are emitted at sorted paths, zip timestamps come from
// the project's createdAt (never "now"), and content is a pure function of the
// bundle — so re-builds hash identically. MANIFEST.json (sha256 of every other
// member) is generated last; the build is then ledgered as export.replication
// with the manifest hash.
import path from "node:path";
import { readFile } from "node:fs/promises";
import { zipSync, strToU8 } from "fflate";
import { ConcordError } from "../core/errors.js";
import { sha256 } from "../core/ids.js";
import * as ledger from "../core/ledger.js";
import { readNdjson } from "../core/store.js";
import { loadAnalysis, loadGoldset, loadRun } from "./methods.js";

function fail(message, details = {}) {
  throw new ConcordError("VALIDATION", message, details);
}

// ---------------------------------------------------------------------- CSV

// RFC 4180: quote any field containing a quote, comma or line break; double
// embedded quotes. Arrays (multilabel) join with "; ".
export function csvField(v) {
  if (v === null || v === undefined) return "";
  const s = Array.isArray(v) ? v.join("; ") : String(v);
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export function toCsv(rows) {
  return rows.map((r) => r.map(csvField).join(",")).join("\n") + "\n";
}

// ------------------------------------------------------------------ helpers

function safeName(name) {
  return String(name ?? "outcome").toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "") || "outcome";
}

async function loadUnitsMap(projectDir, corpusIds) {
  const map = new Map();
  for (const id of corpusIds) {
    const units = await readNdjson(path.join(projectDir, "corpora", id, "units.ndjson"));
    for (const u of units) map.set(u.id, { ...u, corpusId: id });
  }
  return map;
}

// Normalize one analysis into what the reproduce scripts need; null when the
// analysis is not a DSL fit the scripts know how to re-derive.
function dslPlan(analysis, run) {
  const r = analysis.results ?? {};
  if (analysis.level !== "corrected" || !/^dsl/.test(String(r.estimator ?? ""))) return null;
  if (!Array.isArray(r.cells) || r.cells.length === 0) return null;
  const runId = analysis.spec?.runId ?? run?.id;
  const goldsetId = analysis.spec?.goldsetId;
  const corpusId = analysis.spec?.corpusId ?? run?.corpusId;
  if (!runId || !goldsetId || !corpusId) return null;
  return {
    id: analysis.id,
    outcome: safeName(r.outcome ?? analysis.spec?.rows),
    groupBy: r.groupBy ?? analysis.spec?.cols ?? null,
    runId,
    goldsetId,
    corpusId,
    cells: r.cells.map((c) => ({ group: String(c.group), est: c.est, se: c.se, ciLo: c.ciLo, ciHi: c.ciHi, naive: c.naive ?? null })),
    diff: r.diff && typeof r.diff.est === "number"
      ? { a: String(r.diff.a), b: String(r.diff.b), est: r.diff.est, se: r.diff.se }
      : null,
  };
}

// ------------------------------------------------------------ member: texts

function readmeMd(project, analyses, includeGoldText) {
  const lines = [];
  lines.push(`# Replication archive — ${project.name}`);
  lines.push("");
  lines.push("This archive was generated by Concord so that every corrected statistic in the");
  lines.push("study can be reproduced OUTSIDE Concord, from flat files, with public tools.");
  lines.push("It contains the frozen measurement instruments (including full prompt text),");
  lines.push("the codebook, the designed gold sample with inclusion probabilities (pi), the");
  lines.push("machine outputs, all certificate agreement statistics, and the analysis");
  lines.push("specifications with Concord's stored results.");
  lines.push("");
  lines.push("## How to reproduce the corrected estimates");
  lines.push("");
  lines.push("- R: `Rscript reproduce.R` — targets the public `dsl` package (CRAN), which");
  lines.push("  implements the design-based supervised learning estimator. The script reads");
  lines.push("  the CSVs in this archive and prints the corrected fits beside Concord's");
  lines.push("  stored numbers (shown in comments).");
  lines.push("- Python: `python reproduce.py` — implements the DSL pseudo-outcome estimator");
  lines.push("  inline (numpy/pandas, no Concord code) and ASSERTS equality with Concord's");
  lines.push("  stored results to 1e-6.");
  lines.push("");
  lines.push("## Contents");
  lines.push("");
  lines.push("- `codebook.md` — the constructs as frozen for analysis.");
  lines.push("- `instruments/<id>.json` — frozen instrument versions, full payloads and prompts.");
  lines.push("- `dictionaries/<id>.json` — dictionary instruments with complete term lists.");
  lines.push("- `gold/<goldsetId>.csv` — designed sample: unitId, pi, per-coder labels, adjudicated" + (includeGoldText ? ", unit text." : ". Unit text was withheld at export (includeGoldText: false)."));
  lines.push("- `outputs/<runId>.csv` — machine labels: unitId, label, confidence, escalated, cacheHit.");
  lines.push("- `units/<corpusId>.csv` — unit metadata (grouping variables for the analyses; no text).");
  lines.push("- `agreement.json` — calibration certificates: machine-vs-gold and human-vs-human agreement.");
  lines.push("- `analyses/<id>.json` — analysis spec, stored results, evidence links, ladder level.");
  lines.push("- `MANIFEST.json` — sha256 of every member (excluding itself); verify before trusting.");
  lines.push("");
  lines.push("## Provenance");
  lines.push("");
  lines.push(`Project: ${project.name} (id ${project.id}), created ${project.createdAt}.`);
  lines.push(`Analyses included: ${analyses.map((a) => a.id).join(", ")}.`);
  lines.push("Archive timestamps are fixed to the project's creation time so identical");
  lines.push("studies produce byte-identical archives. The export is recorded in the");
  lines.push("project ledger (event type export.replication) with this archive's manifest hash.");
  lines.push("");
  return lines.join("\n");
}

function codebookMd(project) {
  const lines = ["# Codebook", ""];
  for (const c of project.constructs ?? []) {
    lines.push(`## ${c.name} (${c.type})`);
    lines.push("");
    lines.push(c.definition || "(no definition recorded)");
    lines.push("");
    lines.push(`Authored by: ${c.authoredBy}${c.humanTouched ? " (human-reviewed)" : " (not human-reviewed)"}`);
    lines.push("");
    if (c.criteria?.include?.length) {
      lines.push("Include:");
      for (const x of c.criteria.include) lines.push(`- ${x}`);
      lines.push("");
    }
    if (c.criteria?.exclude?.length) {
      lines.push("Exclude:");
      for (const x of c.criteria.exclude) lines.push(`- ${x}`);
      lines.push("");
    }
    if (c.edgeCases?.length) {
      lines.push("Edge cases:");
      for (const x of c.edgeCases) lines.push(`- ${x}`);
      lines.push("");
    }
    if (c.examples?.length) {
      lines.push("Worked examples:");
      for (const ex of c.examples) lines.push(`- [${ex.kind}] label=${csvField(ex.label)} — ${ex.text.replace(/\s+/g, " ")}`);
      lines.push("");
    }
  }
  return lines.join("\n");
}

function goldCsv(goldset, unitsMap, includeGoldText) {
  const coders = [...(goldset.coders ?? [])].sort((a, b) => (a.coderId < b.coderId ? -1 : 1));
  const header = ["unitId", "pi", ...coders.map((c) => `label_${c.coderId}`), "adjudicated"];
  if (includeGoldText) header.push("text");
  const rows = [header];
  for (const s of goldset.sample ?? []) {
    const row = [s.unitId, s.pi];
    for (const c of coders) row.push(c.labels?.[s.unitId] ?? "");
    row.push(goldset.adjudicated?.[s.unitId] ?? "");
    if (includeGoldText) row.push(unitsMap.get(s.unitId)?.text ?? "");
    rows.push(row);
  }
  return toCsv(rows);
}

async function outputsCsv(projectDir, runId) {
  const outputs = await readNdjson(path.join(projectDir, "runs", runId, "outputs.ndjson"));
  const jurors = new Set(outputs.map((o) => o.juror).filter((j) => j !== undefined));
  const multi = jurors.size > 1;
  const header = ["unitId", "label", "confidence", "escalated", "cacheHit"];
  if (multi) header.push("juror");
  const rows = [header];
  for (const o of outputs) {
    const row = [o.unitId, o.label, o.confidence ?? "", o.escalated ?? false, o.cacheHit ?? false];
    if (multi) row.push(o.juror ?? "");
    rows.push(row);
  }
  return toCsv(rows);
}

function unitsCsv(unitsMap, corpusId) {
  const units = [...unitsMap.values()].filter((u) => u.corpusId === corpusId);
  const metaKeys = [...new Set(units.flatMap((u) => Object.keys(u.meta ?? {})))].sort();
  const rows = [["unitId", ...metaKeys]];
  for (const u of units) rows.push([u.id, ...metaKeys.map((k) => u.meta?.[k] ?? "")]);
  return toCsv(rows);
}

// ------------------------------------------------- members: R + Python code

function rScript(plans, project) {
  const L = [];
  L.push("# reproduce.R — re-derive Concord's DSL-corrected estimates with the public");
  L.push("# `dsl` R package (Egami, Hinck, Stewart and Wei; CRAN package `dsl`), which");
  L.push("# implements design-based supervised learning: machine labels on every unit,");
  L.push("# human gold on a designed subsample with known inclusion probabilities.");
  L.push(`# Project: ${project.name} (${project.id})`);
  L.push("#   install.packages(\"dsl\")");
  L.push("library(dsl)");
  L.push("");
  if (plans.length === 0) {
    L.push("# No DSL-corrected analyses were included in this archive; nothing to refit.");
    return L.join("\n") + "\n";
  }
  for (const p of plans) {
    L.push(`# ---- analysis ${p.id}: DSL-corrected proportion of ${p.outcome}${p.groupBy ? ` by ${p.groupBy}` : ""} ----`);
    L.push(`outputs <- read.csv("outputs/${p.runId}.csv")   # machine labels for every unit`);
    L.push(`units   <- read.csv("units/${p.corpusId}.csv")  # unit metadata (grouping variables)`);
    L.push(`gold    <- read.csv("gold/${p.goldsetId}.csv")  # designed gold subsample with pi`);
    L.push(`d <- merge(outputs, units, by = "unitId")`);
    L.push(`d <- merge(d, gold[, c("unitId", "adjudicated", "pi")], by = "unitId", all.x = TRUE)`);
    L.push(`d$${p.outcome}_pred <- d$label        # machine label (prediction)`);
    L.push(`d$${p.outcome} <- d$adjudicated       # human gold; NA off the gold sample`);
    L.push(`# Every unit carries its DESIGN inclusion probability. Under this archive's`);
    L.push(`# sampling design the recorded pi applies to sampled and unsampled units alike.`);
    if (p.uniformPi !== null && p.uniformPi !== undefined) {
      L.push(`d$pi[is.na(d$pi)] <- ${p.uniformPi}`);
    } else {
      L.push(`# (Non-uniform design: fill d$pi for unsampled units from the stratum table.)`);
    }
    const formula = p.groupBy ? `${p.outcome} ~ 0 + factor(${p.groupBy})` : `${p.outcome} ~ 1`;
    L.push("fit <- dsl(model = \"lm\",");
    L.push(`           formula = ${formula},`);
    L.push(`           predicted_var = "${p.outcome}",`);
    L.push(`           prediction = "${p.outcome}_pred",`);
    L.push(`           sample_prob = "pi",`);
    L.push("           data = d)");
    L.push("summary(fit)");
    L.push(`# With 0 + factor(${p.groupBy ?? "1"}) coding each coefficient is a corrected cell`);
    L.push("# proportion. Concord stored (DSL pseudo-outcome mean, sandwich SE):");
    for (const c of p.cells) {
      L.push(`#   ${p.groupBy ?? "all"}=${c.group}: est = ${c.est.toFixed(6)}, se = ${c.se.toFixed(6)}, 95% CI [${c.ciLo.toFixed(6)}, ${c.ciHi.toFixed(6)}]`);
    }
    if (p.diff) {
      L.push(`#   difference ${p.diff.a} - ${p.diff.b}: est = ${p.diff.est.toFixed(6)}, se = ${p.diff.se.toFixed(6)}`);
      L.push(`# (Refit with ${p.outcome} ~ factor(${p.groupBy}) to read the difference as a slope.)`);
    }
    L.push("");
  }
  return L.join("\n") + "\n";
}

function pyScript(plans, project) {
  const L = [];
  L.push("#!/usr/bin/env python3");
  L.push('"""reproduce.py — re-derive Concord\'s DSL-corrected estimates from the archive');
  L.push("CSVs and ASSERT equality with Concord's stored results to 1e-6.");
  L.push("");
  L.push("Estimator (design-based supervised learning / prediction-powered inference;");
  L.push("Egami, Jacobs-Harukawa, Stewart and Wei 2023; Angelopoulos, Bates, Fannjiang,");
  L.push("Jordan and Zrnic 2023): with machine labels yhat on every unit and human gold y");
  L.push("on a designed subsample with inclusion probability pi, the pseudo-outcome");
  L.push("    pseudo_i = yhat_i + (R_i / pi_i) * (y_i - yhat_i)");
  L.push("replaces y in the moment condition. For a proportion: est = mean(pseudo) and");
  L.push("the sandwich variance (A = 1, B = mean((pseudo - est)^2)) gives");
  L.push("    se = sqrt(mean((pseudo - est)^2) / n).");
  L.push("Unbiased regardless of machine-error structure because pi is a design quantity.");
  L.push("");
  L.push(`Project: ${project.name} (${project.id}). Requires numpy and pandas.`);
  L.push('"""');
  L.push("import math");
  L.push("");
  L.push("import numpy as np");
  L.push("import pandas as pd");
  L.push("");
  L.push("");
  L.push("def dsl_proportion(yhat, y, pi):");
  L.push('    """DSL pseudo-outcome mean + sandwich SE. y is NaN off the gold sample."""');
  L.push("    yhat = np.asarray(yhat, dtype=float)");
  L.push("    y = np.asarray(y, dtype=float)");
  L.push("    pi = np.asarray(pi, dtype=float)");
  L.push("    pseudo = yhat.copy()");
  L.push("    gold = ~np.isnan(y)");
  L.push("    pseudo[gold] = yhat[gold] + (y[gold] - yhat[gold]) / pi[gold]");
  L.push("    n = pseudo.size");
  L.push("    est = pseudo.mean()");
  L.push("    b = float(np.mean((pseudo - est) ** 2))  # sandwich middle, A = 1");
  L.push("    return float(est), math.sqrt(b / n)");
  L.push("");
  L.push("");
  L.push("def check(name, got, want, tol=1e-6):");
  L.push('    assert abs(got - want) < tol, f"{name}: recomputed {got!r} != Concord stored {want!r}"');
  L.push('    print(f"  OK {name}: {got:.10f} == {want:.10f} (tol {tol})")');
  L.push("");
  L.push("");
  if (plans.length === 0) {
    L.push('print("No DSL-corrected analyses in this archive; nothing to verify.")');
    return L.join("\n") + "\n";
  }
  for (const p of plans) {
    L.push(`# ---- analysis ${p.id}: corrected proportion of ${p.outcome}${p.groupBy ? ` by ${p.groupBy}` : ""} ----`);
    L.push(`print("analysis ${p.id}")`);
    L.push(`outputs = pd.read_csv("outputs/${p.runId}.csv")`);
    L.push(`units = pd.read_csv("units/${p.corpusId}.csv")`);
    L.push(`gold = pd.read_csv("gold/${p.goldsetId}.csv")`);
    L.push('d = outputs.merge(units, on="unitId").merge(');
    L.push('    gold[["unitId", "adjudicated", "pi"]], on="unitId", how="left")');
    L.push("cells = {}");
    L.push("for group, want_est, want_se in [");
    for (const c of p.cells) {
      L.push(`    (${JSON.stringify(c.group)}, ${String(c.est)}, ${String(c.se)}),`);
    }
    L.push("]:");
    if (p.groupBy) {
      L.push(`    sub = d[d[${JSON.stringify(p.groupBy)}].astype(str) == group]`);
    } else {
      L.push("    sub = d");
    }
    L.push('    est, se = dsl_proportion(sub["label"], sub["adjudicated"], sub["pi"])');
    const groupKey = p.groupBy ?? "cell";
    L.push('    check(f"' + groupKey + '={group} est", est, want_est)');
    L.push('    check(f"' + groupKey + '={group} se", se, want_se)');
    L.push("    cells[group] = (est, se)");
    if (p.diff) {
      L.push(`# corrected difference ${p.diff.a} - ${p.diff.b} (independent groups)`);
      L.push(`est = cells[${JSON.stringify(p.diff.a)}][0] - cells[${JSON.stringify(p.diff.b)}][0]`);
      L.push(`se = math.sqrt(cells[${JSON.stringify(p.diff.a)}][1] ** 2 + cells[${JSON.stringify(p.diff.b)}][1] ** 2)`);
      L.push(`check("diff ${p.diff.a}-${p.diff.b} est", est, ${String(p.diff.est)})`);
      L.push(`check("diff ${p.diff.a}-${p.diff.b} se", se, ${String(p.diff.se)})`);
    }
    L.push("");
  }
  L.push('print("All Concord numbers reproduced to 1e-6.")');
  return L.join("\n") + "\n";
}

// -------------------------------------------------------------------- build

export async function build(project, analysisIds, { projectDir, includeGoldText = true } = {}) {
  if (!project || typeof project !== "object" || !project.id) fail("build requires a project object");
  if (!Array.isArray(analysisIds) || analysisIds.length === 0 || analysisIds.some((a) => typeof a !== "string" || !a)) {
    fail("build requires a non-empty array of analysis ids", { analysisIds });
  }
  if (typeof projectDir !== "string" || !projectDir) fail("build requires options.projectDir");

  const analyses = [];
  for (const id of analysisIds) analyses.push(await loadAnalysis(project, projectDir, id));

  // resolve referenced runs/corpora; load goldsets and units
  const runs = new Map();
  for (const a of analyses) {
    const runId = a.spec?.runId;
    if (runId && !runs.has(runId)) {
      const run = await loadRun(projectDir, runId);
      if (run) runs.set(runId, run);
    }
  }
  const corpusIds = [...new Set([
    ...analyses.map((a) => a.spec?.corpusId).filter(Boolean),
    ...[...runs.values()].map((r) => r.corpusId).filter(Boolean),
  ])];
  const unitsMap = await loadUnitsMap(projectDir, corpusIds);
  const goldsets = [];
  for (const meta of project.goldsets ?? []) {
    const g = await loadGoldset(project, projectDir, meta.id);
    if (g?.sample) goldsets.push(g);
  }

  // reproduce-script plans (one per DSL-corrected analysis)
  const plans = [];
  for (const a of analyses) {
    const plan = dslPlan(a, runs.get(a.spec?.runId));
    if (!plan) continue;
    const gs = goldsets.find((g) => g.id === plan.goldsetId);
    const pis = [...new Set((gs?.sample ?? []).map((x) => x.pi))];
    plan.uniformPi = pis.length === 1 ? pis[0] : null;
    plans.push(plan);
  }

  // ---- members (path → utf8 string)
  const members = new Map();
  members.set("README.md", readmeMd(project, analyses, includeGoldText));
  members.set("codebook.md", codebookMd(project));
  for (const inst of project.instruments ?? []) {
    const member = inst.kind === "dictionary" ? `dictionaries/${inst.id}.json` : `instruments/${inst.id}.json`;
    members.set(member, JSON.stringify(inst, null, 2) + "\n");
  }
  for (const g of goldsets) members.set(`gold/${g.id}.csv`, goldCsv(g, unitsMap, includeGoldText));
  for (const runId of runs.keys()) members.set(`outputs/${runId}.csv`, await outputsCsv(projectDir, runId));
  for (const corpusId of corpusIds) members.set(`units/${corpusId}.csv`, unitsCsv(unitsMap, corpusId));
  members.set("agreement.json", JSON.stringify({
    instruments: (project.instruments ?? []).map((i) => ({
      id: i.id, name: i.name, kind: i.kind, level: i.level, versionHash: i.versionHash,
      frozen: i.frozen ?? false, stability: i.stability ?? null, certificate: i.certificate ?? null,
    })),
    goldsets: goldsets.map((g) => ({
      id: g.id, tier: g.tier, design: g.design, status: g.status,
      n: g.sample?.length ?? 0, humanAgreement: g.humanAgreement ?? null,
    })),
  }, null, 2) + "\n");
  for (const a of analyses) members.set(`analyses/${a.id}.json`, JSON.stringify(a, null, 2) + "\n");
  members.set("reproduce.R", rScript(plans, project));
  members.set("reproduce.py", pyScript(plans, project));

  // ---- MANIFEST last: sha256 of every member, itself excluded
  const files = {};
  for (const p of [...members.keys()].sort()) files[p] = sha256(members.get(p));
  const manifest = {
    format: "concord-replication/1",
    generator: "concord",
    projectId: project.id,
    projectName: project.name,
    slug: project.slug,
    createdAt: project.createdAt,
    analyses: analysisIds,
    includesGoldText: includeGoldText,
    files,
  };
  const manifestStr = JSON.stringify(manifest, null, 2) + "\n";
  members.set("MANIFEST.json", manifestStr);

  // ---- deterministic zip: sorted paths, mtime from project.createdAt
  let mtime = new Date(project.createdAt ?? "2000-01-01T00:00:00.000Z");
  if (Number.isNaN(mtime.getTime()) || mtime.getFullYear() < 1980) mtime = new Date("2000-01-01T00:00:00.000Z");
  const zippable = {};
  for (const p of [...members.keys()].sort()) zippable[p] = strToU8(members.get(p));
  const zipBuffer = Buffer.from(zipSync(zippable, { level: 6, mtime }));

  await ledger.append(projectDir, "system", "export.replication", { projectId: project.id }, {
    manifestHash: sha256(manifestStr),
    analyses: analysisIds,
    files: members.size,
    includesGoldText: includeGoldText,
  });

  return { zipBuffer, manifest };
}
