// Replication archive builder. Everything a stranger needs to reproduce every
// corrected statistic OUTSIDE Concord: frozen instruments (full prompts),
// the codebook, gold labels with inclusion probabilities, machine outputs,
// certificate agreement stats, analysis specs/results, and generated R +
// Python scripts that re-derive the DSL-corrected estimates from the CSVs.
//
// Determinism: members are emitted at sorted paths, zip timestamps come from
// the project's createdAt (never "now"), and content is a pure function of the
// bundle — so re-builds hash identically. MANIFEST.json (sha256 of every other
// member) is generated last; the build is then ledgered as export.replication
// with the manifest hash.
import path from "node:path";
import { readFile } from "node:fs/promises";
import { zipSync, strToU8 } from "fflate";
import { ConcordError } from "../core/errors.js";
import { sha256 } from "../core/ids.js";
import * as ledger from "../core/ledger.js";
import { readNdjson } from "../core/store.js";
import { loadAnalysis, loadGoldset, loadRun } from "./methods.js";

function fail(message, details = {}) {
  throw new ConcordError("VALIDATION", message, details);
}

// ---------------------------------------------------------------------- CSV

// RFC 4180: quote any field containing a quote, comma or line break; double
// embedded quotes. Arrays (multilabel) join with "; ".
//
// Formula-injection hardening: a TEXT cell beginning with =, +, - or @ gets a
// leading apostrophe so spreadsheet apps will not execute it as a formula.
// Numbers and booleans are never prefixed (they must parse numerically in
// R/pandas). The convention is documented in the archive README.
export function csvField(v) {
  if (v === null || v === undefined) return "";
  let s = Array.isArray(v) ? v.join("; ") : String(v);
  if (typeof v !== "number" && typeof v !== "boolean" && /^[=+\-@]/.test(s)) s = `'${s}`;
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export function toCsv(rows) {
  return rows.map((r) => r.map(csvField).join(",")).join("\n") + "\n";
}

// ------------------------------------------------------------------ helpers

function safeName(name) {
  return String(name ?? "outcome").toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "") || "outcome";
}

async function loadUnitsMap(projectDir, corpusIds) {
  const map = new Map();
  for (const id of corpusIds) {
    const units = await readNdjson(path.join(projectDir, "corpora", id, "units.ndjson"));
    for (const u of units) map.set(u.id, { ...u, corpusId: id });
  }
  return map;
}

// Normalize one analysis into what the reproduce scripts need; null when the
// analysis is not a DSL fit the scripts know how to re-derive.
function dslPlan(analysis, run) {
  const r = analysis.results ?? {};
  const estimator = r.estimator ?? analysis.spec?.estimator ?? "";
  if (analysis.level !== "corrected" || !/^dsl/.test(String(estimator))) return null;
  if (!Array.isArray(r.cells) || r.cells.length === 0) return null;
  const runId = analysis.spec?.runId ?? run?.id;
  const goldsetId = analysis.spec?.goldsetId;
  const corpusId = analysis.spec?.corpusId ?? run?.corpusId;
  if (!runId || !goldsetId || !corpusId) return null;
  return {
    id: analysis.id,
    outcome: safeName(r.outcome ?? analysis.spec?.rows),
    groupBy: r.groupBy ?? analysis.spec?.cols ?? null,
    runId,
    goldsetId,
    corpusId,
    cells: r.cells.map((c) => ({ group: String(c.group), est: c.est, se: c.se, ciLo: c.ciLo, ciHi: c.ciHi, naive: c.naive ?? null })),
    diff: r.diff && typeof r.diff.est === "number"
      ? { a: String(r.diff.a), b: String(r.diff.b), est: r.diff.est, se: r.diff.se }
      : null,
  };
}

// ------------------------------------------------------------ member: texts

function readmeMd(project, analyses, includeGoldText) {
  const lines = [];
  lines.push(`# Replication archive — ${project.name}`);
  lines.push("");
  lines.push("This archive was generated by Concord so that every corrected statistic in the");
  lines.push("study can be reproduced OUTSIDE Concord, from flat files, with public tools.");
  lines.push("It contains the frozen measurement instruments (including full prompt text),");
  lines.push("the codebook, the designed gold sample with inclusion probabilities (pi), the");
  lines.push("machine outputs, all certificate agreement statistics, and the analysis");
  lines.push("specifications with Concord's stored results.");
  lines.push("");
  lines.push("## How to reproduce the corrected estimates");
  lines.push("");
  lines.push("- R: `Rscript reproduce.R` — computes the DSL pseudo-outcome estimator INLINE");
  lines.push("  in base R and ASSERTS near-equality (1e-6) with Concord's stored results via");
  lines.push("  stopifnot. The public `dsl` package (CRAN) is then run as a clearly labeled");
  lines.push("  methodological cross-check: same estimand, different machinery, so it is not");
  lines.push("  expected to match to printed precision and may fail on tiny gold samples.");
  lines.push("- Python: `python reproduce.py` — implements the DSL pseudo-outcome estimator");
  lines.push("  inline (numpy/pandas, no Concord code) and ASSERTS equality with Concord's");
  lines.push("  stored results to 1e-6.");
  lines.push("");
  lines.push("Panel runs: `outputs/<runId>.csv` then carries a `juror` column with one row");
  lines.push("per juror per unit PLUS one row with juror == \"aggregate\" — the panel's");
  lines.push("aggregated verdict, which is the label Concord analyzes. Both reproduce");
  lines.push("scripts filter to the aggregate rows before merging; do the same in your own");
  lines.push("reanalysis or every unit will be duplicated.");
  lines.push("");
  lines.push("CSV conventions: unit-meta columns are prefixed `meta_` so merges can never");
  lines.push("collide with unitId/label/pi/adjudicated. To block spreadsheet formula");
  lines.push("injection, any TEXT cell beginning with =, +, - or @ carries a leading");
  lines.push("apostrophe (') — strip it when consuming such cells as raw text; numeric");
  lines.push("cells are never prefixed.");
  lines.push("");
  lines.push("## Contents");
  lines.push("");
  lines.push("- `codebook.md` — the constructs as frozen for analysis.");
  lines.push("- `instruments/<id>.json` — frozen instrument versions, full payloads and prompts.");
  lines.push("- `dictionaries/<id>.json` — dictionary instruments with complete term lists.");
  lines.push("- `gold/<goldsetId>.csv` — designed sample: unitId, pi, per-coder labels, adjudicated" + (includeGoldText ? ", unit text." : ". Unit text was withheld at export (includeGoldText: false)."));
  lines.push("- `outputs/<runId>.csv` — machine labels: unitId, label, confidence, escalated, cacheHit");
  lines.push("  (+ a `juror` column for panel runs; see the panel note above).");
  lines.push("- `units/<corpusId>.csv` — unit metadata (grouping variables for the analyses; no");
  lines.push("  text). Meta columns carry the `meta_` prefix.");
  lines.push("- `agreement.json` — calibration certificates: machine-vs-gold and human-vs-human agreement.");
  lines.push("- `analyses/<id>.json` — analysis spec, stored results, evidence links, ladder level.");
  lines.push("- `MANIFEST.json` — sha256 of every member (excluding itself); verify before trusting.");
  lines.push("");
  lines.push("## Provenance");
  lines.push("");
  lines.push(`Project: ${project.name} (id ${project.id}), created ${project.createdAt}.`);
  lines.push(`Analyses included: ${analyses.map((a) => a.id).join(", ")}.`);
  lines.push("Archive timestamps are fixed to the project's creation time so identical");
  lines.push("studies produce byte-identical archives. The export is recorded in the");
  lines.push("project ledger (event type export.replication) with this archive's manifest hash.");
  lines.push("");
  return lines.join("\n");
}

function codebookMd(project) {
  const lines = ["# Codebook", ""];
  for (const c of project.constructs ?? []) {
    lines.push(`## ${c.name} (${c.type})`);
    lines.push("");
    lines.push(c.definition || "(no definition recorded)");
    lines.push("");
    lines.push(`Authored by: ${c.authoredBy}${c.humanTouched ? " (human-reviewed)" : " (not human-reviewed)"}`);
    lines.push("");
    if (c.criteria?.include?.length) {
      lines.push("Include:");
      for (const x of c.criteria.include) lines.push(`- ${x}`);
      lines.push("");
    }
    if (c.criteria?.exclude?.length) {
      lines.push("Exclude:");
      for (const x of c.criteria.exclude) lines.push(`- ${x}`);
      lines.push("");
    }
    if (c.edgeCases?.length) {
      lines.push("Edge cases:");
      for (const x of c.edgeCases) lines.push(`- ${x}`);
      lines.push("");
    }
    if (c.examples?.length) {
      lines.push("Worked examples:");
      for (const ex of c.examples) lines.push(`- [${ex.kind}] label=${csvField(ex.label)} — ${ex.text.replace(/\s+/g, " ")}`);
      lines.push("");
    }
  }
  return lines.join("\n");
}

function goldCsv(goldset, unitsMap, includeGoldText) {
  const coders = [...(goldset.coders ?? [])].sort((a, b) => (a.coderId < b.coderId ? -1 : 1));
  const header = ["unitId", "pi", ...coders.map((c) => `label_${c.coderId}`), "adjudicated"];
  if (includeGoldText) header.push("text");
  const rows = [header];
  for (const s of goldset.sample ?? []) {
    const row = [s.unitId, s.pi];
    for (const c of coders) row.push(c.labels?.[s.unitId] ?? "");
    row.push(goldset.adjudicated?.[s.unitId] ?? "");
    if (includeGoldText) row.push(unitsMap.get(s.unitId)?.text ?? "");
    rows.push(row);
  }
  return toCsv(rows);
}

async function outputsCsv(projectDir, runId) {
  const outputs = await readNdjson(path.join(projectDir, "runs", runId, "outputs.ndjson"));
  const jurors = new Set(outputs.map((o) => o.juror).filter((j) => j !== undefined));
  const multi = jurors.size > 1;
  const header = ["unitId", "label", "confidence", "escalated", "cacheHit"];
  if (multi) header.push("juror");
  const rows = [header];
  for (const o of outputs) {
    const row = [o.unitId, o.label, o.confidence ?? "", o.escalated ?? false, o.cacheHit ?? false];
    if (multi) row.push(o.juror ?? "");
    rows.push(row);
  }
  return toCsv(rows);
}

// Unit meta carries arbitrary researcher keys — including, possibly, "label",
// "pi", "adjudicated" or "unitId". The meta_ prefix keeps the reproduce-script
// merges collision-free by construction (documented in the README).
function unitsCsv(unitsMap, corpusId) {
  const units = [...unitsMap.values()].filter((u) => u.corpusId === corpusId);
  const metaKeys = [...new Set(units.flatMap((u) => Object.keys(u.meta ?? {})))].sort();
  const rows = [["unitId", ...metaKeys.map((k) => `meta_${k}`)]];
  for (const u of units) rows.push([u.id, ...metaKeys.map((k) => u.meta?.[k] ?? "")]);
  return toCsv(rows);
}

// ------------------------------------------------- members: R + Python code

function rScript(plans, project) {
  const L = [];
  L.push("# reproduce.R — verify Concord's DSL-corrected estimates OUTSIDE Concord.");
  L.push("#");
  L.push("# PRIMARY VERIFICATION (base R, no packages): the design-based supervised");
  L.push("# learning pseudo-outcome estimator (Egami, Hinck, Stewart, and Wei (2023);");
  L.push("# Angelopoulos, Bates, Fannjiang, Jordan, and Zrnic (2023)) is computed");
  L.push("# INLINE below — pseudo = yhat + (y - yhat)/pi on gold rows, else yhat; a");
  L.push("# cell's estimate is mean(pseudo) with HC0 sandwich");
  L.push("# se = sqrt(mean((pseudo - est)^2)/n) — and stopifnot asserts near-equality");
  L.push("# with Concord's stored numbers to 1e-6.");
  L.push("#");
  L.push("# METHODOLOGICAL CROSS-CHECK (optional): each block ends by refitting the");
  L.push("# same estimand with the public CRAN dsl package. Its SuperLearner-anchored");
  L.push("# estimator (grf random forests, cross-fitting, internal randomness) targets");
  L.push("# the same estimand but will not match Concord's numbers to printed");
  L.push("# precision, and may fail outright on tiny gold samples. A cross-check");
  L.push("# failure does NOT invalidate the stopifnot verification above it.");
  L.push(`# Project: ${project.name} (${project.id})`);
  L.push("#   install.packages(\"dsl\")");
  L.push("");
  if (plans.length === 0) {
    L.push("# No DSL-corrected analyses were included in this archive; nothing to refit.");
    return L.join("\n") + "\n";
  }
  for (const p of plans) {
    const col = p.groupBy ? `meta_${p.groupBy}` : null;
    L.push(`# ---- analysis ${p.id}: DSL-corrected proportion of ${p.outcome}${p.groupBy ? ` by ${p.groupBy}` : ""} ----`);
    L.push(`outputs <- read.csv("outputs/${p.runId}.csv", check.names = FALSE)  # machine labels`);
    L.push(`units   <- read.csv("units/${p.corpusId}.csv", check.names = FALSE) # unit meta (meta_ prefixed)`);
    L.push(`gold    <- read.csv("gold/${p.goldsetId}.csv", check.names = FALSE) # designed gold subsample with pi`);
    L.push(`# Panel runs write one row per juror per unit PLUS one row with juror ==`);
    L.push(`# "aggregate" — the panel's aggregated verdict, which is the label Concord`);
    L.push(`# analyzes. Keep only aggregate rows, or the merges below duplicate units.`);
    L.push(`if ("juror" %in% names(outputs)) outputs <- subset(outputs, juror == "aggregate")`);
    L.push(`d <- merge(outputs, units, by = "unitId")`);
    L.push(`d <- merge(d, gold[, c("unitId", "adjudicated", "pi")], by = "unitId", all.x = TRUE)`);
    L.push(`# (meta columns are meta_ prefixed in units.csv, so these merges cannot`);
    L.push(`# collide with unitId/label/pi/adjudicated)`);
    L.push(`d$${p.outcome}_pred <- d$label        # machine label (prediction)`);
    L.push(`d$${p.outcome} <- d$adjudicated       # human gold; NA off the gold sample`);
    L.push(`# The inline estimator uses pi only on gold rows, where the CSV records it.`);
    L.push(`# The dsl() cross-check needs pi on every row; under this archive's design`);
    L.push(`# the recorded pi applies to sampled and unsampled units alike.`);
    if (p.uniformPi !== null && p.uniformPi !== undefined) {
      L.push(`d$pi[is.na(d$pi)] <- ${p.uniformPi}`);
    } else {
      L.push(`# (Non-uniform design: fill d$pi for unsampled units from the stratum table`);
      L.push(`# before running the cross-check.)`);
    }
    L.push("");
    L.push("# inline pseudo-outcome estimator + verification");
    L.push(`d$pseudo <- d$${p.outcome}_pred`);
    L.push(`on_gold <- !is.na(d$${p.outcome})`);
    L.push(`d$pseudo[on_gold] <- d$${p.outcome}_pred[on_gold] +`);
    L.push(`  (d$${p.outcome}[on_gold] - d$${p.outcome}_pred[on_gold]) / d$pi[on_gold]`);
    p.cells.forEach((c, i) => {
      const k = i + 1;
      L.push(col
        ? `ps <- d$pseudo[as.character(d[["${col}"]]) == ${JSON.stringify(c.group)}]`
        : "ps <- d$pseudo");
      L.push(`est_${k} <- mean(ps)`);
      L.push(`se_${k} <- sqrt(mean((ps - est_${k})^2) / length(ps))`);
      L.push(`stopifnot(abs(est_${k} - ${String(c.est)}) < 1e-6, abs(se_${k} - ${String(c.se)}) < 1e-6)`);
    });
    if (p.diff) {
      const ia = p.cells.findIndex((c) => c.group === p.diff.a) + 1;
      const ib = p.cells.findIndex((c) => c.group === p.diff.b) + 1;
      if (ia > 0 && ib > 0) {
        L.push(`# corrected difference ${p.diff.a} - ${p.diff.b} (independent groups)`);
        L.push(`est_diff <- est_${ia} - est_${ib}`);
        L.push(`se_diff <- sqrt(se_${ia}^2 + se_${ib}^2)`);
        L.push(`stopifnot(abs(est_diff - ${String(p.diff.est)}) < 1e-6, abs(se_diff - ${String(p.diff.se)}) < 1e-6)`);
      }
    }
    L.push(`cat("OK: analysis ${p.id} reproduced Concord's stored numbers to 1e-6\\n")`);
    L.push("# Concord stored (DSL pseudo-outcome mean, HC0 sandwich SE):");
    for (const c of p.cells) {
      L.push(`#   ${p.groupBy ?? "all"}=${c.group}: est = ${c.est.toFixed(6)}, se = ${c.se.toFixed(6)}, 95% CI [${c.ciLo.toFixed(6)}, ${c.ciHi.toFixed(6)}]`);
    }
    if (p.diff) {
      L.push(`#   difference ${p.diff.a} - ${p.diff.b}: est = ${p.diff.est.toFixed(6)}, se = ${p.diff.se.toFixed(6)}`);
    }
    L.push("");
    L.push("# ---- METHODOLOGICAL CROSS-CHECK (not the verification) ----");
    L.push("# The CRAN dsl package refits the same estimand with its own machinery");
    L.push("# (SuperLearner-anchored outcome models via grf, cross-fitting, internal");
    L.push("# randomness). Even with the pinned seed it will not match the numbers");
    L.push("# above to printed precision, and it may fail on tiny gold samples (too");
    L.push("# few gold rows per fold). Args pinned for the record; failure here does");
    L.push("# not invalidate the stopifnot verification above.");
    if (p.groupBy) {
      L.push("# Factor coding note: with ~ 0 + factor(.) each coefficient is a cell");
      L.push("# proportion. With treatment coding (~ factor(.)) R takes the");
      L.push("# alphabetically first level as the reference and each slope estimates");
      L.push("# (level - reference), so a printed difference may need its sign flipped");
      const ref = [...p.cells.map((c) => c.group)].sort()[0];
      if (p.diff && p.cells.length === 2) {
        const flips = ref === p.diff.a;
        L.push(`# relative to the ${p.diff.a} - ${p.diff.b} contrast: here the reference is "${ref}",`);
        L.push(flips
          ? `# so the treatment-coded slope estimates ${p.diff.b} - ${p.diff.a} — the NEGATIVE of`
          : `# so the treatment-coded slope estimates ${p.diff.a} - ${p.diff.b} — the same sign as`);
        L.push("# the difference verified above.");
      } else {
        L.push(`# relative to a reported contrast (the reference here would be "${ref}").`);
      }
    }
    const formula = col ? `${p.outcome} ~ 0 + factor(\`${col}\`)` : `${p.outcome} ~ 1`;
    L.push("cross_check <- tryCatch({");
    L.push("  library(dsl)");
    L.push("  set.seed(20231201)");
    L.push("  fit <- dsl(model = \"lm\",");
    L.push(`             formula = ${formula},`);
    L.push(`             predicted_var = "${p.outcome}",`);
    L.push(`             prediction = "${p.outcome}_pred",`);
    L.push(`             sample_prob = "pi",`);
    L.push("             data = d)");
    L.push("  print(summary(fit))");
    L.push('}, error = function(e) message("dsl cross-check skipped: ", conditionMessage(e)))');
    L.push("");
  }
  return L.join("\n") + "\n";
}

function pyScript(plans, project) {
  const L = [];
  L.push("#!/usr/bin/env python3");
  L.push('"""reproduce.py — re-derive Concord\'s DSL-corrected estimates from the archive');
  L.push("CSVs and ASSERT equality with Concord's stored results to 1e-6.");
  L.push("");
  L.push("Estimator (design-based supervised learning / prediction-powered inference;");
  L.push("Egami, Hinck, Stewart, and Wei (2023); Angelopoulos, Bates, Fannjiang,");
  L.push("Jordan, and Zrnic (2023)): with machine labels yhat on every unit and human gold y");
  L.push("on a designed subsample with inclusion probability pi, the pseudo-outcome");
  L.push("    pseudo_i = yhat_i + (R_i / pi_i) * (y_i - yhat_i)");
  L.push("replaces y in the moment condition. For a proportion: est = mean(pseudo) and");
  L.push("the sandwich variance (A = 1, B = mean((pseudo - est)^2)) gives");
  L.push("    se = sqrt(mean((pseudo - est)^2) / n).");
  L.push("Unbiased regardless of machine-error structure because pi is a design quantity.");
  L.push("");
  L.push(`Project: ${project.name} (${project.id}). Requires numpy and pandas.`);
  L.push('"""');
  L.push("import math");
  L.push("");
  L.push("import numpy as np");
  L.push("import pandas as pd");
  L.push("");
  L.push("");
  L.push("def dsl_proportion(yhat, y, pi):");
  L.push('    """DSL pseudo-outcome mean + sandwich SE. y is NaN off the gold sample."""');
  L.push("    yhat = np.asarray(yhat, dtype=float)");
  L.push("    y = np.asarray(y, dtype=float)");
  L.push("    pi = np.asarray(pi, dtype=float)");
  L.push("    pseudo = yhat.copy()");
  L.push("    gold = ~np.isnan(y)");
  L.push("    pseudo[gold] = yhat[gold] + (y[gold] - yhat[gold]) / pi[gold]");
  L.push("    n = pseudo.size");
  L.push("    est = pseudo.mean()");
  L.push("    b = float(np.mean((pseudo - est) ** 2))  # sandwich middle, A = 1");
  L.push("    return float(est), math.sqrt(b / n)");
  L.push("");
  L.push("");
  L.push("def check(name, got, want, tol=1e-6):");
  L.push('    assert abs(got - want) < tol, f"{name}: recomputed {got!r} != Concord stored {want!r}"');
  L.push('    print(f"  OK {name}: {got:.10f} == {want:.10f} (tol {tol})")');
  L.push("");
  L.push("");
  if (plans.length === 0) {
    L.push('print("No DSL-corrected analyses in this archive; nothing to verify.")');
    return L.join("\n") + "\n";
  }
  for (const p of plans) {
    L.push(`# ---- analysis ${p.id}: corrected proportion of ${p.outcome}${p.groupBy ? ` by ${p.groupBy}` : ""} ----`);
    L.push(`print("analysis ${p.id}")`);
    L.push(`outputs = pd.read_csv("outputs/${p.runId}.csv")`);
    L.push("# Panel runs write one row per juror per unit PLUS one row with");
    L.push('# juror == "aggregate" — the panel\'s aggregated verdict, which is the label');
    L.push("# Concord analyzes. Keep only aggregate rows, or the merges below would");
    L.push("# duplicate every unit and silently corrupt the estimates.");
    L.push('if "juror" in outputs.columns:');
    L.push('    outputs = outputs[outputs["juror"] == "aggregate"]');
    L.push(`units = pd.read_csv("units/${p.corpusId}.csv")  # unit meta (meta_ prefixed)`);
    L.push(`gold = pd.read_csv("gold/${p.goldsetId}.csv")`);
    L.push('d = outputs.merge(units, on="unitId").merge(');
    L.push('    gold[["unitId", "adjudicated", "pi"]], on="unitId", how="left")');
    L.push("cells = {}");
    L.push("for group, want_est, want_se in [");
    for (const c of p.cells) {
      L.push(`    (${JSON.stringify(c.group)}, ${String(c.est)}, ${String(c.se)}),`);
    }
    L.push("]:");
    if (p.groupBy) {
      L.push(`    sub = d[d[${JSON.stringify(`meta_${p.groupBy}`)}].astype(str) == group]`);
    } else {
      L.push("    sub = d");
    }
    L.push('    est, se = dsl_proportion(sub["label"], sub["adjudicated"], sub["pi"])');
    const groupKey = p.groupBy ?? "cell";
    L.push('    check(f"' + groupKey + '={group} est", est, want_est)');
    L.push('    check(f"' + groupKey + '={group} se", se, want_se)');
    L.push("    cells[group] = (est, se)");
    if (p.diff) {
      L.push(`# corrected difference ${p.diff.a} - ${p.diff.b} (independent groups)`);
      L.push(`est = cells[${JSON.stringify(p.diff.a)}][0] - cells[${JSON.stringify(p.diff.b)}][0]`);
      L.push(`se = math.sqrt(cells[${JSON.stringify(p.diff.a)}][1] ** 2 + cells[${JSON.stringify(p.diff.b)}][1] ** 2)`);
      L.push(`check("diff ${p.diff.a}-${p.diff.b} est", est, ${String(p.diff.est)})`);
      L.push(`check("diff ${p.diff.a}-${p.diff.b} se", se, ${String(p.diff.se)})`);
    }
    L.push("");
  }
  L.push('print("All Concord numbers reproduced to 1e-6.")');
  return L.join("\n") + "\n";
}

// -------------------------------------------------------------------- build

export async function build(project, analysisIds, { projectDir, includeGoldText = true } = {}) {
  if (!project || typeof project !== "object" || !project.id) fail("build requires a project object");
  if (!Array.isArray(analysisIds) || analysisIds.length === 0 || analysisIds.some((a) => typeof a !== "string" || !a)) {
    fail("build requires a non-empty array of analysis ids", { analysisIds });
  }
  if (typeof projectDir !== "string" || !projectDir) fail("build requires options.projectDir");

  const analyses = [];
  for (const id of analysisIds) analyses.push(await loadAnalysis(project, projectDir, id));

  // resolve referenced runs/corpora; load goldsets and units
  const runs = new Map();
  for (const a of analyses) {
    const runId = a.spec?.runId;
    if (runId && !runs.has(runId)) {
      const run = await loadRun(projectDir, runId);
      if (run) runs.set(runId, run);
    }
  }
  const corpusIds = [...new Set([
    ...analyses.map((a) => a.spec?.corpusId).filter(Boolean),
    ...[...runs.values()].map((r) => r.corpusId).filter(Boolean),
  ])];
  const unitsMap = await loadUnitsMap(projectDir, corpusIds);
  const goldsets = [];
  for (const meta of project.goldsets ?? []) {
    const g = await loadGoldset(project, projectDir, meta.id);
    if (g?.sample) goldsets.push(g);
  }

  // reproduce-script plans (one per DSL-corrected analysis)
  const plans = [];
  for (const a of analyses) {
    const plan = dslPlan(a, runs.get(a.spec?.runId));
    if (!plan) continue;
    const gs = goldsets.find((g) => g.id === plan.goldsetId);
    const pis = [...new Set((gs?.sample ?? []).map((x) => x.pi))];
    plan.uniformPi = pis.length === 1 ? pis[0] : null;
    plans.push(plan);
  }

  // ---- members (path → utf8 string)
  const members = new Map();
  members.set("README.md", readmeMd(project, analyses, includeGoldText));
  members.set("codebook.md", codebookMd(project));
  for (const inst of project.instruments ?? []) {
    const member = inst.kind === "dictionary" ? `dictionaries/${inst.id}.json` : `instruments/${inst.id}.json`;
    members.set(member, JSON.stringify(inst, null, 2) + "\n");
  }
  for (const g of goldsets) members.set(`gold/${g.id}.csv`, goldCsv(g, unitsMap, includeGoldText));
  for (const runId of runs.keys()) members.set(`outputs/${runId}.csv`, await outputsCsv(projectDir, runId));
  for (const corpusId of corpusIds) members.set(`units/${corpusId}.csv`, unitsCsv(unitsMap, corpusId));
  members.set("agreement.json", JSON.stringify({
    instruments: (project.instruments ?? []).map((i) => ({
      id: i.id, name: i.name, kind: i.kind, level: i.level, versionHash: i.versionHash,
      frozen: i.frozen ?? false, stability: i.stability ?? null, certificate: i.certificate ?? null,
    })),
    goldsets: goldsets.map((g) => ({
      id: g.id, tier: g.tier, design: g.design, status: g.status,
      n: g.sample?.length ?? 0, humanAgreement: g.humanAgreement ?? null,
    })),
  }, null, 2) + "\n");
  for (const a of analyses) members.set(`analyses/${a.id}.json`, JSON.stringify(a, null, 2) + "\n");
  members.set("reproduce.R", rScript(plans, project));
  members.set("reproduce.py", pyScript(plans, project));

  // ---- MANIFEST last: sha256 of every member, itself excluded
  const files = {};
  for (const p of [...members.keys()].sort()) files[p] = sha256(members.get(p));
  const manifest = {
    format: "concord-replication/1",
    generator: "concord",
    projectId: project.id,
    projectName: project.name,
    slug: project.slug,
    createdAt: project.createdAt,
    analyses: analysisIds,
    includesGoldText: includeGoldText,
    files,
  };
  const manifestStr = JSON.stringify(manifest, null, 2) + "\n";
  members.set("MANIFEST.json", manifestStr);

  // ---- deterministic zip: sorted paths, mtime from project.createdAt
  let mtime = new Date(project.createdAt ?? "2000-01-01T00:00:00.000Z");
  if (Number.isNaN(mtime.getTime()) || mtime.getFullYear() < 1980) mtime = new Date("2000-01-01T00:00:00.000Z");
  const zippable = {};
  for (const p of [...members.keys()].sort()) zippable[p] = strToU8(members.get(p));
  const zipBuffer = Buffer.from(zipSync(zippable, { level: 6, mtime }));

  await ledger.append(projectDir, "system", "export.replication", { projectId: project.id }, {
    manifestHash: sha256(manifestStr),
    analyses: analysisIds,
    files: members.size,
    includesGoldText: includeGoldText,
  });

  return { zipBuffer, manifest };
}
